### ISSUE TITLE
Utilizar interpolaciones específicas del lenguaje

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-bibliotheca#111]
Ahora que el laboratorio utiliza los comentarios propios de cada lenguaje en la interpolación de las soluciones anteriores (https://github.com/mumuki/mumuki-laboratory/issues/656), la biblioteca debería hacer lo mismo.

**Comment by fedescarpa** [comment]
fixed in https://github.com/mumuki/mumuki-bibliotheca/commit/259cbb285cc4d81a092f817109e62a85ce8e9636
