### ISSUE TITLE
No se puede guardar la opción correcta en ejercicio de Selección Única

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-bibliotheca#115]
Al intentar guardar un ejercicio de selección única recién creado, tira como error "No debe seleccionar ninguna opción". Además el diskette queda en rojo.

En cambio, si se crea el ejercicio como de Selección Múltiple y luego se lo cambia a Única no hay ningún problema al guardarlo. 

![image](https://user-images.githubusercontent.com/7552150/34494388-0d4c2c36-efcf-11e7-9eca-af4a516dc874.png)

**Comment by fedescarpa** [comment]
If exercise language is different to `text` every choice should be e piece of code to be execued by the runnner.

If you want to write free text in the options and mark one as correct, the exercise language should be text.
