### ISSUE TITLE
No aparece la sección de "Opciones" al crear un nuevo ejercicio de selección múltiple o única

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-bibliotheca#121]
Al crear un nuevo problema de "selección múltiple" o "selección única" no aparece automáticamente la sección de Evaluación para agregar las Opciones. Hay que cambiar de ejercicio y volver para que aparezca. 

![image](https://user-images.githubusercontent.com/7552150/36260510-6ad3b7c8-1240-11e8-80df-14a37d528898.png)

**Comment by rodri042** [comment]
Ya no pasa más: https://www.youtube.com/watch?v=LXydSTceh3o

Si pifié en algo vuelvan a abrirlo, pero me parece que este issue es demasiado viejo (8 meses) y esto ya recuerdo que venía funcionando OK
