### ISSUE TITLE
Support input of block-oriented exercises

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-bibliotheca#123]
We need to support blockly inputs for the following fields: 
  * default content 
  * extra content

**Comment by flbulgarelli** [comment]
Also we must add support for recognizing primitives in extra content, so that student can use them.

**Comment by luchotc** [comment]
Moving the last part to an issue in laboratory

**Comment by flbulgarelli** [comment]
Done in https://github.com/mumuki/mumuki-bibliotheca/pull/133
