### ISSUE TITLE
Support gobstones attires input

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-bibliotheca#124]
We need a way to: 

* upload the attires
* indicate that the exercise will use it 
   * :up: this seems to have being solved with `<gs-attire>`

**Comment by luchotc** [comment]
@flbulgarelli 
Wasn't this solved by adding the component gs-attire or are we still looking a better way to enter attires? 
If so, we should also include the toolbox as it uses a similar approach

**Comment by flbulgarelli** [comment]
Two more comments: 

* Entering attires manually is a pain in the neck. I need a button that allows you to define the `attire.json` - uploading the images if possible - and adding the proper `gs-attire` tag
* The same applies for the gobstones toolbox.
