### ISSUE TITLE
Se borra todo el contenido al cambiar el "tipo de ejercicio" e ir y volver de otro

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-bibliotheca#131]
Genero un nuevo ejercicio que se crea automáticamente como "Problema"; escribo el contenido, y si le cambio el "tipo de ejercicio" a "Lectura", no puedo guardarlo porque dice que la descripción está vacía. 

![image](https://user-images.githubusercontent.com/7552150/36847229-700dc268-1d3c-11e8-9e01-6d8409423f22.png)

Cambié de ejercicio y volví para ver si podía guardarlo, pero se borra todo y vuelve a verse como "Problema".

![image](https://user-images.githubusercontent.com/7552150/36847339-c0bec450-1d3c-11e8-8a91-80179a04d03f.png)

**Comment by rodri042** [comment]
No lo pude reproducir, https://www.youtube.com/watch?v=AtnAA_c-srQ

**Comment by flbulgarelli** [comment]
@NadiaFinzi?
