### ISSUE TITLE
Error en enunciado: Numero de parámetros -Programación Funcional Leccion 9 Ejercicio 13

### ISSUE THREAD

**Issue by NahuelOvejero** [mumuki/mumuki-bibliotheca#134]
![params](https://user-images.githubusercontent.com/23706776/37259511-f96ebfae-2565-11e8-91c3-2dce6f41a460.jpg)

Indica que hay que definir hayAlgunNegativo/2, pero solo debe poseer 1 parámetro, la lista.

**Comment by julian-berbel** [comment]
Tenés toda la razón. Ya lo arreglé.

Gracias por el feedback!
