### ISSUE TITLE
Extra code in gobstones has always a program block

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-bibliotheca#135]

**Comment by aguspina** [comment]
Blockly layout has always a program block.

extra code program block + solution program block => produces gobstones error

**Comment by luchotc** [comment]
The problem is that the editor starts with an empty program in biblio.
We have two options:
1) Add a property to the custom-editor to allow the editor to start without any block
2) Handle this scenario in the runner

The first one is a lot more simpler. Thoughts? @flbulgarelli @aguspina

**Comment by aguspina** [comment]
Hey @flbulgarelli, you didn't got the issue. It's ok that editor in
laboratory starts with the program block. The problem is that the extra
code editor in bibliotheca starts with the same block too.

**Comment by flbulgarelli** [comment]
Oops hahah.

**Comment by luchotc** [comment]
@flbulgarelli 
So, what option do you think is the best?

**Comment by flbulgarelli** [comment]
> Add a property to the custom-editor to allow the editor to start without any block

Ok, lets go for this.
