### ISSUE TITLE
No se puede validar la posición del cabezal en kids

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-bibliotheca#146]
Lo que repercute en los primeros 4 5 ejercicios de primaria, en los que solo te enseñan el bloque Mover.

**Comment by flbulgarelli** [comment]
Es cierto. Ojo porque esto va en contra de https://github.com/mumuki/mumuki-bibliotheca-api/issues/102. Sucede que cuando encaramos ese issue, nunca pensamos en ese escenario :confused: 

Habría que revertir este cambio: 
https://github.com/mumuki/mumuki-bibliotheca/blob/1a8084ac1c2b4dc23fd4e4352c37b5dc0e6e6863/src/scripts/services/languages-service.js#L45

**Comment by flbulgarelli** [comment]
Fixed by https://github.com/mumuki/mumuki-bibliotheca/pull/155
