### ISSUE TITLE
Al crear un procedimiento con parametros en extra_code luego en labo aparece para usar sin parametros

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-bibliotheca#153]
Dejo los screenshots correspondientes
Biblio extra_code:
<img width="208" alt="screen shot 2018-05-28 at 11 25 20" src="https://user-images.githubusercontent.com/4105740/40619118-3557e414-626a-11e8-9e3b-8e8e440930f7.png">

Labo toolbox:
<img width="77" alt="screen shot 2018-05-28 at 11 25 51" src="https://user-images.githubusercontent.com/4105740/40619133-48c69f36-626a-11e8-8d2e-0bcc5910aa27.png">

**Comment by rodri042** [comment]
Eso también pasa en Gobstones Web, por cómo está hecho todo ahora, hay que nombrar a ese procedimiento como: `VolarAl_` y ahí debería andar.

Los cambios de camelcase se traducen a espacios y los guiones bajos a "agujeritos" de parámetros a la hora de crear los bloques de llamadas

**Comment by flbulgarelli** [comment]
So this is basically a  _won't fix_, right?

**Comment by flbulgarelli** [comment]
@rodri042 ?

**Comment by rodri042** [comment]
Yes!
