### ISSUE TITLE
Problemas con ejercicios que no son problem y assistance rules

### ISSUE THREAD

**Issue by rgonzalezt** [mumuki/mumuki-bibliotheca#162]
Cuando una guía tiene ejercicios que no son problem, blbiotheca ui le manda a bibliotheca api un assistance rules vacío (lo cual está mal) y api expone eso y no lo filtra (lo cual está mal) y eso hace que rompa labo.

**Comment by flbulgarelli** [comment]
Un detalle: los asstance rules NO tienen sentido para los ejercicios de tipo `reading` o `playground`, porque no tienen ningún tipo de feedback. 

Por otro lado, al final no está rompiendo labo en estos escenarios, dado que todos los ejercicios soportan `assistance_rules` en la clase `Exercise`.
