### ISSUE TITLE
Tras dejar expectativas incompletas y cambiar de ejercicio, se rompen al regresar

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-bibliotheca#164]
Se crearon reglas y expectativas que se dejaron en blanco. Al cambiar de ejercicio y volver, las expectativas se ven como en la captura; y no se pueden eliminar.

![image](https://user-images.githubusercontent.com/7552150/42590367-ffbf45d6-8519-11e8-8a9a-6d0ea83d4643.png)

Luego, al tocar sobre alguna de las "expectativas" que aparecen, salta este cartel:

![image](https://user-images.githubusercontent.com/7552150/42590467-40d14fb0-851a-11e8-8a69-ec93a0641263.png)

@fedescarpa

**Comment by fedescarpa** [comment]
I can't reproduce this issue in production and locally
