### ISSUE TITLE
No se guarda la interpolación del default code

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-bibliotheca#184]
Hice varios ejercicios con interpolación de la solución anterior y no se está guardando esa selección. 

Al entrar al ejercicio, está vacío. Me fijé en biblio, y aparecía el default code en "custom"; lo cambié a interpolación, actualicé todo y seguía igual. Al actualizar biblio, nuevamente el default code se encontraba en custom. 

Dejo un [video ](https://youtu.be/zBLb3ZMQhlM) que hice reproduciendo el error.
[Default code.zip](https://github.com/mumuki/mumuki-bibliotheca/files/2288054/Default.code.zip)

@julian-berbel

**Comment by NadiaFinzi** [comment]
Los ejercicios que tienen default y extra code andan bien, pero en biblio al poner "default code" desaparece todo lo que esté hecho en el extra. Al ir al extra y volver al default aparecen los bloques pero desordenados, distinto a como lo había dejado. 

Dejo otro [video](https://youtu.be/E0m5Dxvtmr4).
[Extra code.zip](https://github.com/mumuki/mumuki-bibliotheca/files/2291363/Extra.code.zip)

**Comment by rodri042** [comment]
@NadiaFinzi Los videos no funcan :(

**Comment by NadiaFinzi** [comment]
El [issue del default code](https://github.com/mumuki/mumuki-bibliotheca/issues/184#issue-350543075) lo "solucionamos" agregando un espacio después del `/*...previousSolution...*/`.

**Comment by flbulgarelli** [comment]
> El issue del default code lo "solucionamos" agregando un espacio después del /*...previousSolution...*/.

¿@rodri042 esto cambia algo? ¿permite hacer menor hackeril al fix que propusiste?

**Comment by rodri042** [comment]
@flbulgarelli Hmm no creo. El problema que arreglé yo es que cuando el editor era 'custom' marcaba por default el option de 'Custom editor', que levanta blockly y esto sí o sí pisa todo lo que haya en 'Interpolations', perdiendo así el contenido

**Comment by flbulgarelli** [comment]
Entonces quizás lo que comenta @NadiaFinzi sea otro bug, más general y común a todos los editores, que consiste en que no guarda esa interpolación hasta que se agrega un espacio. Tengo entiendo que eso es un bug estructural de Angular/ACE y la forma que insertamos texto programáticamente en los editores (¿no, @fedescarpa?). @NadiaFinzi @aguspina si lo pueden confirmar, ¿suben un issue?

**Comment by NadiaFinzi** [comment]
Con @julian-berbel lo habíamos probado y no se estaba mandando nada, como si no hubiera hecho ningún cambio. Por eso hicimos lo del espacio, pero como eso puede ser cualquier cosa que represente un verdadero cambio en el default code.

**Comment by fedescarpa** [comment]
Tiene que ser lo que decis @flbulgarelli, Insertar programaticamente código en ace es bastante choto ya que no triggerea un update, hay que hacerlo a mano. @rodri042 arreglo eso en el markdown toolbar, tal vez es hacer lo mismo para esto... habría que probar
