### ISSUE TITLE
El editor de UI de gobstones al crear un nuevo ejercicio se ve roto

### ISSUE THREAD

**Issue by rodri042** [mumuki/mumuki-bibliotheca#221]
Hace rato que me viene pasando eso, ahora chequeé y pasa también en producción.

Video: https://www.youtube.com/watch?v=nfViKk57ccM

**Comment by flbulgarelli** [comment]
Si, es lo mismo que está acá reportado: https://github.com/mumuki/mumuki-bibliotheca/issues/195
