### ISSUE TITLE
Say chapter instead of topic in the main screen?

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-bibliotheca#31]
I know that for us they are different things, but for the standard user they are almost the same thing (and the word topic is a bit confusing).

What about keeping _topic_ internal and just saying _chapter_ everywhere?

**Comment by faloi** [comment]
Seems like Nico agrees...

![25007033](https://cloud.githubusercontent.com/assets/1585835/21376479/2a064f3a-c714-11e6-859c-efecae1cc8bd.jpg)

**Comment by fedescarpa** [comment]
@faloi, I agree with you

**Comment by faloi** [comment]
@flbulgarelli ?

**Comment by flbulgarelli** [comment]
I am generally against naming things in the object and user mode different. Moreover, here we are proposing to change the wording of just one of the core content elements - topic, guide, book. I feel this inconsistent, confusing and error prone for the programmer. 

If  we think that the term `topic` is not the best, I vote for discussing the model, not just the ui.

**Comment by flbulgarelli** [comment]
Also, please consider the following facts: 

* the new ui has not been tested with hundreds or dozens uf user, so the assertion _topic is a confusing word_ is perhaps too strong
* the old editor had no translation and the editors saw and english ui. Now spanish editors are going to see another word - `tema`.

**Comment by flbulgarelli** [comment]
Closing since there was no further discussion.
