### ISSUE TITLE
Collaborators can not be edited

### ISSUE THREAD

**Issue by estefaniamiguel** [mumuki/mumuki-bibliotheca#60]
Hello!
Recently I've edited some exercises and I cannot change the collaborators. Maybe the collaborators feature is not longer working, but well, I let you know!

BTW, i love the new editor! Is freaking awesome!

**Comment by flbulgarelli** [comment]
Hi!

I actually can edit the Collaborators. But the issue here is that it is single line instead of multiline, which makes difficult to edit them.

**Comment by flbulgarelli** [comment]
Closing due to previous comment. 

See https://github.com/mumuki/mumuki-bibliotheca/issues/73
