### ISSUE TITLE
Extra space in code insertion

### ISSUE THREAD

**Issue by JessSaavedra** [mumuki/mumuki-bibliotheca#79]
When I select some lines of code and then click on the code icon, the autogenerated markdown leaves an extra space between the quotes and the word language and the user has to manually remove it to see the syntax highlight.

For example:

<code>
``` language
</code>

<br>
<br>
When it should be
<br>
<br>
<code>
```language
</code>

**Comment by luchotc** [comment]
It was introduced on purpose by @fedescarpa and it works fine
