### ISSUE TITLE
Loading page issues 

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-bibliotheca#86]
There are some issues when loading bibliotheca.mumuki.io from https: 

* All google fonts are loaded from http, thus raising mixed content errors
* After a deployment, page is not completely reloaded even after a refresh, thus rendering inconsistent views. Only disable cache from web tools  is making the page load properly.

**Comment by fedescarpa** [comment]
fixes in https://github.com/mumuki/mumuki-bibliotheca/commit/16face9a2b5c132e01e510397fa8dbda0d721f87

**Comment by flbulgarelli** [comment]
But does this fix the reloading issues?

**Comment by flbulgarelli** [comment]
@fedescarpa

**Comment by fedescarpa** [comment]
Yes
