### ISSUE TITLE
Can't modify an exercise

### ISSUE THREAD

**Issue by estefaniamiguel** [mumuki/mumuki-bibliotheca#93]
I am trying to modify this exercise:

https://bibliotheca.mumuki.io/#/guides/wollok/mumuki-guia-objetos-introduccion-primeros-pasos/exercises/33

But it says I don't have the right permissions.
I need to clarify some Wollok exercise since students don't get them.

How can I do it?
Thanks!

**Comment by flbulgarelli** [comment]
Hi @estefaniamiguel 

You were lacking editing permissions over wollok organization. Now you have them :)
